### ISSUE TITLE
When no face are found, server is write an error message to log

### ISSUE THREAD

**Issue by elad-bar** [codeproject/CodeProject.AI-Server#28]
Can't reopen the original issue, cloning #12 

With latest version we have again the same issue:
`Error Face Processing: No face found in image`

**Comment by ChrisMaunder** [comment]
Can you please send me the pic that contains a face you would expect it to spot, plus the current settings you're using?

**Comment by elad-bar** [comment]
Pretty simple, when no face available in the picture it throws that error, I already provided you solution for that, you have added it and then revert it

**Comment by ChrisMaunder** [comment]
This has been fixed

**Comment by elad-bar** [comment]
this issue was not fixed, still error, still success=false
![image](https://user-images.githubusercontent.com/3207137/213442971-6b4ed68f-8243-4dba-8124-07d3f6303e25.png)
